### ISSUE TITLE
database credentials

### ISSUE THREAD

**Issue by AtitBimali** [JoshuaKasa/Replica#1]
Let's say I converted the script to `.exe` and ran it into my device and my files are locked. What if I again converted the `.exe` to python file and obtain the **database credentials**. Won't I be able to access the db and get they decryption key ?

**Comment by JoshuaKasa** [comment]
Yes, you could. But remember that when a Python file is converted into .exe, the original source code is converted into machine code that is specific to the operating system and architecture for which the .exe file was compiled. So, it is not possible to convert it back to it's original code. You could partially reverse engineer it by reading the asembly code for it, but I don't think that would be enough for getting the hardcoded password. Btw, I don't have any ideas on how to prevent that if that's possible  😅  If you have any ideas you can make a pull request! Thanks for the comment <3

**Comment by AtitBimali** [comment]
Oh, my bad! 
I was complete unaware of that. I think storing the key in database is fine if we make limit the access to that database by filtering IP.
